project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "channel.qmd"
    - "comments_user.qmd"
    - "comments_sentiment.qmd"

website:
  title: "youtube"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



